export const CHANGE_OFFSET_MONITORS = 'CHANGE_OFFSET_MONITORS'
export const CHANGE_OFFSET_CAMERAS = 'CHANGE_OFFSET_CAMERAS'
export const RECIVE_PRODUCTS = 'RECIVE_PRODUCTS'
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const SET_FILTER_MONITORS = 'SET_FILTER_MONITORS';
export const SET_FILTER_CAMERAS = 'SET_FILTER_CAMERAS';
export const SET_FILTER_NAME = 'SET_FILTER_NAME';
export const COUNTS_LOAD = 'COUNTS_LOAD';
